supersuit/action_transforms/continuous_action_ops.py

So it looks like continuous actions do not work in SB3 because of the unbounded action space. So I bounded it. Not sure if -10 to 10 is perfect, but it seems to give plenty of room for the softmax to really differentiate between the options while not being too large.

fixed continuous action bounds

---

supersuit/parallel_wrappers.py

Yeah, turns out the parallel frame skip wrapper also broke during the API changes, but I didn't notice.
The ideal solution here is to remove this wrapper, and bootstrap the aec frame skip wrapper (like most of the wrappers in supersuit), but I'll have to check that this works as expected and doesn't have performance issues.

fixed parallel frame skip wrapper

---

README.md
supersuit/utils/wrapper_chooser.py
supersuit/vector/vector_constructors.py
test/pettingzoo_api_test.py
test/test_vector/test_aec_vector_identity_env.py
test/test_vector/test_aec_vector_values.py
test/test_vector/test_pettingzoo_to_vec.py
test/test_vector/test_render.py
test/test_vector/test_vector_dict.py

This implements a rename fix as per [the change made in PettingZoo](https://github.com/Farama-Foundation/PettingZoo/pull/604). Tests are expected to fail until the pull from PettingZoo side is made.

Rename from_parallel and to_parallel as per change in pettingzoo

---

supersuit/generic_wrappers/frame_skip.py

Now that gym is able to give warnings, Supersuit is showing some warnings from using some soon-to-be deprecated functions. This PR is just an attempt to squash some of them.

Fix some deprecation warnings

---

supersuit/vector/constructors.py

Specifically, helps with variable numbers of agents in the differnet constructors, something like this:
```
venv = MakeCPUAsyncConstructor(3)([make_env_fn(n_walkers=2), make_env_fn(n_walkers=3), make_env_fn(n_walkers=7), ], observation_space=example_env.observation_space(example_env.possible_agents[0]), action_space=example_env.action_space(example_env.possible_agents[0]),tot_num_envs=2+3+7,metadata={})
```

removed unnecessary assert check

---

supersuit/lambda_wrappers/observation_lambda.py
supersuit/lambda_wrappers/reward_lambda.py
supersuit/vector/multiproc_vec.py
test/dummy_aec_env.py
test/gym_mock_test.py
test/parallel_env_test.py
test/vec_env_test.py

This updates the lambda wrappers to the latest truncation termination API, and updates a bunch of the tests too.
AFAIK, this PR is done, as `test_vector` and `test_utils` files requies `aec_wrappers` and `utils` to be updated in a separate PR.
Tests for this PR _will not pass_ because of #165.

Update Lambda wrappers and fix a bunch of the tests

---

requirements.txt
sanity_checks/agent_indication_tests.py
sanity_checks/base_aec_tests.py
sanity_checks/black_death_tests.py
sanity_checks/minimal_working_env.py
sanity_checks/padding_tests.py
setup.py
supersuit/__init__.py
supersuit/aec_vector/async_vector_env.py
supersuit/aec_vector/vector_env.py
supersuit/generic_wrappers/frame_skip.py
supersuit/multiagent_wrappers/black_death.py
supersuit/utils/base_aec_wrapper.py
supersuit/vector/concat_vec_env.py
supersuit/vector/markov_vector_wrapper.py
supersuit/vector/multiproc_vec.py
supersuit/vector/single_vec_env.py
test/dummy_gym_env.py
test/gym_mock_test.py
test/test_vector/test_aec_vector_identity_env.py
test/test_vector/test_aec_vector_values.py
test/test_vector/test_env_is_wrapped.py
test/test_vector/test_gym_vector.py
test/test_vector/test_pettingzoo_to_vec.py
test/test_vector/test_vector_dict.py

Includes a probable bugfix for AECVector wrapper.

Multiagent wrappers, tests, vecenv, aecenv fixes & more

---

setup.py
test/aec_mock_test.py

Using `np.equal` in tests gives `TypeError: No loop matching the specified signature and casting was found for ufunc equal` with numpy 1.24.
This changes it with `np.array_equal` instead.

fix: np.equal in test

---

supersuit/generic_wrappers/delay_observations.py
supersuit/generic_wrappers/frame_skip.py
supersuit/generic_wrappers/frame_stack.py
supersuit/generic_wrappers/max_observation.py
supersuit/generic_wrappers/nan_wrappers.py
supersuit/generic_wrappers/sticky_actions.py
supersuit/generic_wrappers/utils/base_modifier.py
supersuit/generic_wrappers/utils/shared_wrapper_util.py
supersuit/lambda_wrappers/observation_lambda.py
supersuit/lambda_wrappers/reward_lambda.py
supersuit/multiagent_wrappers/black_death.py
supersuit/utils/base_aec_wrapper.py
supersuit/vector/concat_vec_env.py
supersuit/vector/markov_vector_wrapper.py
supersuit/vector/multiproc_vec.py
supersuit/vector/sb3_vector_wrapper.py
supersuit/vector/sb_vector_wrapper.py
supersuit/vector/single_vec_env.py
test/dummy_aec_env.py
test/dummy_gym_env.py
test/parallel_env_test.py

This is in conjunction with [this](https://github.com/Farama-Foundation/PettingZoo/issues/889).

remove return info

---

setup.py
supersuit/generic_wrappers/utils/shared_wrapper_util.py
supersuit/lambda_wrappers/observation_lambda.py
supersuit/multiagent_wrappers/black_death.py
supersuit/utils/base_aec_wrapper.py
supersuit/utils/basic_transforms/normalize_obs.py
supersuit/vector/concat_vec_env.py
supersuit/vector/markov_vector_wrapper.py
supersuit/vector/multiproc_vec.py
supersuit/vector/single_vec_env.py
test/dummy_gym_env.py
test/generated_agents_test.py
test/gym_mock_test.py
test/parallel_env_test.py
test/test_vector/test_pettingzoo_to_vec.py
test/test_vector/test_vector_dict.py

This PR fixes a number of issues with both PettingZoo and current Gymnasium versions. Much of the code in SuperSuit uses `obs = env.reset()` rather than `obs, info = env.reset()`, so I had to adapt things to work.

Change usages of reset() to obs, info = reset()

---

supersuit/vector/multiproc_vec.py
supersuit/vector/sb3_vector_wrapper.py

This solves this issue https://github.com/Farama-Foundation/SuperSuit/issues/217
Here's code to test this out:
```
from stable_baselines3.ppo import CnnPolicy
from stable_baselines3 import PPO
from pettingzoo.butterfly import pistonball_v6
import supersuit as ss
env = pistonball_v6.parallel_env(n_pistons=20, time_penalty=-0.1, continuous=True, random_drop=True, random_rotate=True, ball_mass=0.75, ball_friction=0.3, ball_elasticity=1.5, max_cycles=125)
env = ss.color_reduction_v0(env, mode='B')
env = ss.resize_v1(env, x_size=84, y_size=84)
env = ss.frame_stack_v1(env, 3)
env = ss.pettingzoo_env_to_vec_env_v1(env)
env = ss.concat_vec_envs_v1(env, 8, num_cpus=4, base_class='stable_baselines3')
model = PPO(CnnPolicy, env, verbose=3, gamma=0.95, n_steps=256, ent_coef=0.0905168, …
```

Fix SB3VecEnvWrapper and ProcConcatVec to work with SB3 v2.0.0

---

supersuit/__init__.py
supersuit/vector/multiproc_vec.py

This updates the code from https://github.com/Farama-Foundation/SuperSuit/pull/208 to work with the current master branch. I independently found that the ProcConcatVec env didn't close and couldn't figure out the solution myself, but found this PR from a few months ago seems to address it. Running CI to see if it works now.

ProcConcatVec close fix

---

supersuit/vector/sb3_vector_wrapper.py

This fixes an issue where the wrapper was returning both obs and info, but SB3 only expected observation (see https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/vec_env/dummy_vec_env.py#L76)

Standardize sb3 vec env wrapper to match DummyVecEnv reset() function

---

supersuit/vector/sb3_vector_wrapper.py

This PR fixes the render() method not matching the signature as SB3's VecEnvWrapper class, fixing #223

Add render method with same signature as SB3 underlying class

---

test/test_vector/test_pettingzoo_to_vec_gymnasium_wrappers.py

Minor PR to test that Gymnasium wrappers like NormalizeObservation work on pettingzoo envs which are wrapped to vector envs through concat_vec_env

Add test to check that Gymnasium wrappers work as well on vector envs

---

supersuit/vector/concat_vec_env.py
supersuit/vector/markov_vector_wrapper.py
supersuit/vector/multiproc_vec.py
supersuit/vector/single_vec_env.py
test/dummy_aec_env.py

Just extending https://github.com/Farama-Foundation/SuperSuit/pull/234 to fix a few tricky issues that I was able to solve locally (don't have edit access to that branch but this still gives authorship credit)

Fix render_mode for ProcConcatVec envs

---

supersuit/vector/concat_vec_env.py
supersuit/vector/markov_vector_wrapper.py
supersuit/vector/multiproc_vec.py

Since the `render()` function no longer takes a `mode` parameter, `ProcConcatVec` could not call `render()`. This is a simple PR to fix that. `mode` is replaced by the `render_mode` attribute of the vec env (which also needs to be copied from the parent env by the `ConcatVecEnv` class.
I'm unsure whether different `render_mode`s should also be returning something (e.g. should ansi render modes also return something?). With this PR I've just kept the logic the same as the previous version.

Fix rendering for ProcConcatVec envs

---

supersuit/vector/markov_vector_wrapper.py
test/test_vector/test_pettingzoo_to_vec.py

Closes https://github.com/Farama-Foundation/SuperSuit/issues/232. 
This allows access to `terminal_observation`, which previously wasn't possible when using pettingzoo_env_to_vec_env_v1/MarkovVectorEnv.

fix: have access to `terminal_observation` in the infos.

---

pyproject.toml
supersuit/vector/sb3_vector_wrapper.py
test/test_vector/test_render.py

This is the same as https://github.com/Farama-Foundation/SuperSuit/pull/242 but with pre commit and enabling the old test which was commented out

Fix render_mode attribute not being set by sb3 wrapper

---

supersuit/utils/agent_indicator.py
test/aec_mock_test.py

Fixes the agent indicator so that it works with envs that have unbounded spaces (space.high=np.inf) e.g. simple spread. 
Closes https://github.com/Farama-Foundation/SuperSuit/issues/239.

Fix agent indicator inf bounded spaces

---

supersuit/vector/multiproc_vec.py

Closes https://github.com/Farama-Foundation/SuperSuit/issues/244.

fix: remove unnecessary output when closing mp pipes.

---

.github/workflows/linux-test.yml
pyproject.toml
supersuit/vector/vector_constructors.py
test/test_vector/test_pettingzoo_to_vec_gymnasium_wrappers.py

This PR bumps up the minimum gymnasium version to 1.0.0 and fixes test cases due to the version change.
For the diff in supersuit/vector/vector_constructors.py, in gymnasium's SyncVectorEnv's constructor argument has changed so that it'll implicitly infer the environment's observation space and action space by default, so we don't need to pass them as arguments anymore.
For the diff in test/test_vector/test_pettingzoo_to_vec_gymnasium_wrappers.py, we see a similar issue we saw in PettingZoo in https://github.com/Farama-Foundation/PettingZoo/pull/1272, where gymnasium now requires env's passed into its wrappers to be under the base class `gym.Env`. As a quick and dirty workaround, we dynamically add gym.Env as its base class.

Bump Gymnasium version to 1.0.0 and fix test cases due to the version bump
