supersuit/base_aec_wrapper.py
test/dummy_aec_env.py

Removed agent order (should be merged and released with https://github.com/PettingZoo-Team/PettingZoo/pull/105)

removed agent order

---

supersuit/action_transforms/continuous_action_ops.py
supersuit/action_transforms/homogenize_ops.py

Very minor fixes in pad_action_space and pad_observations to make them faster when nothing is being done. Also removes a bad print statement.

Pad performance improvements

---

supersuit/basic_transforms/color_reduction.py

removed the warning about bad performance because performance is now not noticeably slower

greatly improved color reduction performance

---

README.md
supersuit/vector/aec_rollout.py
supersuit/vector_constructors.py
test/vec_env_test.py

I'm still not sure if this really belongs in supersuit because 
1. It is not a wrapper
2. It is fairly trivial
3. It has ugly dependency issue
The first problem is fairly serious I think. What is supersuit really about? Is it a generic, do it all sort of rl helper library? Or is it about providing environment wrappers? I am inclined to think that a more constrained idea of what it provides makes these libraries easier to work with.

added vector environment constructors

---

requirements.txt
supersuit/base_aec_wrapper.py

A sane fix that unfortunately requires https://github.com/PettingZoo-Team/PettingZoo/pull/140 to be merged and released before tests pass. 
This is required to support the final() solution here: https://github.com/PettingZoo-Team/PettingZoo/pull/139

updated basewrapper to use pettingzoo's base wrapper

---

requirements.txt
setup.py
supersuit/basic_transforms/resize.py

Helps smooth out the installation process. 
cv2 is slightly slower (likely due to lack of avx support in binaries)

Replaces lycon with cv2

---

README.md
requirements.txt
supersuit/__init__.py
supersuit/aec_wrappers.py
supersuit/gym_wrappers.py
supersuit/parallel_wrappers.py
test/aec_mock_test.py
test/dummy_aec_env.py
test/gym_mock_test.py
test/parallel_env_test.py
test/pettingzoo_api_test.py

* Added seed method to appropriate wrappers
* Wrapper level versioning

Versioning

---

requirements.txt
setup.py
supersuit/adv_transforms/agent_indicator.py
supersuit/base_aec_wrapper.py
test/pettingzoo_api_test.py

Catches bug in #40 and also other issues.

added pettingzoo api test for all wrappers and associated fixes

---

README.md
supersuit/__init__.py
supersuit/aec_wrappers.py
test/aec_mock_test.py

Now this PR removes the wrapper from pettingzoo

cyclically expansive learning removal

---

requirements.txt
setup.py
supersuit/vector_constructors.py

added cloudpickle as dependency, made vector constructors use cloudpickle

---

supersuit/__init__.py
supersuit/aec_wrappers.py
test/test_vector/test_pettingzoo_to_vec.py

fixed black death assertion bug

---

supersuit/vector_constructors.py

Hi, I noticed a comment that needed updating to represent a change in the file layout of pettingzoo

Update comment for pettingzoo_env_to_vec_env()

---

supersuit/gym_wrappers.py
test/gym_mock_test.py

Fixed bug reported in #62  and added a test to test the buggy case.

fixed action_lambda bug

---

supersuit/vector/constructors.py
supersuit/vector/markov_vector_wrapper.py
supersuit/vector/multiproc_vec.py
test/test_vector/test_aec_vector_identity_env.py
test/test_vector/test_gym_vector.py

Addresses  https://github.com/PettingZoo-Team/SuperSuit/issues/72

fixed vector environment bugs

---

README.md
supersuit/__init__.py
supersuit/vector/multiproc_vec.py

Added note to inform users about issue noted in #75

Multiprocessing doc add

---

supersuit/vector_constructors.py
test/test_vector/test_gym_vector.py

Fixed #89 
Adds test to verify it has been fixed.

fixed seeding issue for vector environments

---

supersuit/vector/utils/shared_array.py

fixed multiprocessing issue

---

README.md
requirements.txt
setup.py
supersuit/__init__.py
supersuit/vector/concat_vec_env.py
supersuit/vector/markov_vector_wrapper.py
supersuit/vector/multiproc_vec.py
test/aec_mock_test.py
test/dummy_aec_env.py
test/dummy_gym_env.py
test/test_utils/test_basic_transforms/test_color_reduction.py
test/test_utils/test_basic_transforms/test_normalized_obs.py
test/test_utils/test_basic_transforms/test_resize.py
test/test_vector/test_vector_dict.py

Specifically includes changes to dict and tuple spaces

Old master

---

README.md
supersuit/__init__.py
supersuit/multiagent_wrappers/__init__.py
supersuit/multiagent_wrappers/black_death.py
test/aec_mock_test.py
test/generated_agents_test.py
test/pettingzoo_api_test.py
test/test_vector/test_pettingzoo_to_vec.py

Fixed black death wrapper

---

test/aec_unwrapped_test.py
test/dummy_aec_env.py
test/gym_unwrapped_test.py

This adds unwrapped tests for both Gym and AEC environments.

Add unwrapped tests

---

supersuit/__init__.py
supersuit/generic_wrappers/__init__.py
supersuit/generic_wrappers/utils/shared_wrapper_util.py
test/aec_mock_test.py
test/gym_mock_test.py
test/pettingzoo_api_test.py

Updated all `resize_v0` to `resize_v1`

---

supersuit/vector/markov_vector_wrapper.py

This fixes the out of date assertation message in #172.

Fix out of date assertation message

---

supersuit/generic_wrappers/frame_skip.py

The only modified file is frame_skip.py. This update is to match the Gym update using terminations and truncations

Updating Generic Wrappers to the new Gym API

---

.github/workflows/build-publish.yml
.github/workflows/linux-test.yml

Following https://github.com/openai/gym/pull/3094, this adds explicit permissions for the GitHub workflows for PRs.

Update security permissions for GitHub workflows

---

test/pettingzoo_api_test.py
test/test_vector/test_aec_vector_values.py
test/test_vector/test_env_is_wrapped.py
test/test_vector/test_gym_vector.py
test/test_vector/test_pettingzoo_to_vec.py

This PR updates the PettingZoo MPE envs to work with the new 1.23.0 release

Update MPE envs

---

supersuit/__init__.py

Bump version to 3.9.1

---

real_pettingzoo_env_test.py
supersuit/utils/base_aec_wrapper.py
test/pettingzoo_env_test.py

Fix truncations logic error in base_aec_wrapper.py
